In [1]:
import pandas as pd
import numpy as np

In [2]:
df_2020 = pd.read_csv('Parking_Violations_Issued_-_Fiscal_Year_2020.csv')
df_2020.head()

/Users/gary/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (18,29,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1477633194,J58JKX,NJ,PAS,05/08/1972 12:00:00 AM,16,SDN,HONDA,P,8730,...,BK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
1,1449715424,KRE6058,PA,PAS,08/29/1977 12:00:00 AM,98,SUBN,ME/BE,P,86530,...,BLK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
2,1455779155,444326R,NJ,PAS,10/03/1988 12:00:00 AM,20,SDN,LEXUS,P,27030,...,BLACK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
3,1458800908,F728330,OH,PAS,01/03/1990 12:00:00 AM,21,SDN,CHEVR,P,33030,...,NaN,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
4,1466038676,FMY9090,NY,PAS,02/14/1990 12:00:00 AM,21,SUBN,JEEP,S,45130,...,GREY,0.0,2015,-,0,NaN,NaN,NaN,NaN,NaN

In [4]:
df_2021 = pd.read_csv('Parking_Violations_Issued_-_Fiscal_Year_2021.csv')
df_2021.head()

/Users/gary/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (17,18,20,22,23,29,30,31,32,36,38,39) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1471497410,HZH8177,NY,PAS,07/02/2020,20,SUBN,NISSA,P,62200,...,GRAY,0.0,2018,-,0,NaN,NaN,NaN,NaN,NaN
1,1471497630,JCX5781,NY,PAS,06/27/2020,20,P-U,DODGE,P,60790,...,BLU,0.0,2018,-,0,NaN,NaN,NaN,NaN,NaN
2,1471497641,HEK2391,NY,PAS,06/27/2020,20,SUBN,KIA,P,60790,...,BLU,0.0,2020,-,0,NaN,NaN,NaN,NaN,NaN
3,1471497653,GWY9859,NY,PAS,06/27/2020,20,SUBN,JEEP,P,60790,...,BLK,0.0,2009,-,0,NaN,NaN,NaN,NaN,NaN
4,1471497665,HEZ5501,NY,PAS,06/27/2020,20,SUBN,SUBAR,P,60790,...,BLK,0.0,2015,-,0,NaN,NaN,NaN,NaN,NaN

In [5]:
df_2020['Issue Date']= pd.to_datetime(df_2020['Issue Date']) 
df_2021['Issue Date']= pd.to_datetime(df_2021['Issue Date'])

In [6]:
df_2020['Year'] = df_2020['Issue Date'].dt.year 
df_2020['Month'] = df_2020['Issue Date'].dt.month
df_2020['Day'] = df_2020['Issue Date'].dt.day
df_2021['Year'] = df_2021['Issue Date'].dt.year 
df_2021['Month'] = df_2021['Issue Date'].dt.month
df_2021['Day'] = df_2021['Issue Date'].dt.day

In [7]:
df_2020_sp = df_2020[df_2020['Year'] == 2020]
df_2020_sp

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation,Year,Month,Day
7414872,5109306230,88009,NY,MED,2020-01-01,7,SUBN,JEEP,V,0,...,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN,2020,1,1
7414906,5109308240,LCH6921,PA,PAS,2020-01-01,7,SW,CHEVR,V,0,...,NaN,0,NaN,FAILURE TO STOP AT RED LIGHT,NaN,NaN,NaN,2020,1,1
7415278,5600024162,EHM3610,NY,PAS,2020-01-02,12,SUBN,MAZDA,V,0,...,NaN,0,NaN,MOBILE BUS LANE VIOLATION,NaN,NaN,NaN,2020,1,2
7415312,5600024150,AB64604,CT,PAS,2020-01-02,12,PK,TOYOT,V,0,...,NaN,0,NaN,MOBILE BUS LANE VIOLATION,NaN,NaN,NaN,2020,1,2
7415785,5600024046,T713131C,NY,OMT,2020-01-02,12,4DSD,NISSA,V,0,...,NaN,0,NaN,MOBILE BUS LANE VIOLATION,NaN,NaN,NaN,2020,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495377,1475296769,T764428C,NY,OMT,2020-12-31,18,SDN,HONDA,P,13610,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,12,31
12495378,1457738302,Y100808C,NY,OMT,2020-12-31,98,TAXI,NISSA,P,26790,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,12,31
12495379,1455431308,DDH3509,NY,PAS,2020-12-31,71,SUBN,LEXUS,P,0,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,12,31
12495380,1448310430,M54FDG,NJ,PAS,2020-12-31,98,SDN,JEEP,P,5930,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,12,31
12495381,1460080543,GKM2944,NY,PAS,2020-12-31,98,SDN,HONDA,P,28890,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,12,31

In [8]:
df_2020_fa = df_2021[df_2021['Year'] == 2020]
df_2020_fa

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation,Year,Month,Day
0,1471497410,HZH8177,NY,PAS,2020-07-02,20,SUBN,NISSA,P,62200,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,7,2
1,1471497630,JCX5781,NY,PAS,2020-06-27,20,P-U,DODGE,P,60790,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,27
2,1471497641,HEK2391,NY,PAS,2020-06-27,20,SUBN,KIA,P,60790,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,27
3,1471497653,GWY9859,NY,PAS,2020-06-27,20,SUBN,JEEP,P,60790,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,27
4,1471497665,HEZ5501,NY,PAS,2020-06-27,20,SUBN,SUBAR,P,60790,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13915967,1483067257,XHBZ35,NJ,PAS,2020-06-03,78,VAN,DODGE,P,0,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,3
13924296,1481897366,BLANKPLATE,99,999,2020-06-03,99,NaN,NaN,P,16890,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,3
13927721,1481908704,KHP5533,NY,PAS,2020-06-06,40,VAN,HONDA,P,66290,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,6
13933057,1483308613,929935R,NJ,PAS,2020-06-20,20,VAN,FORD,P,0,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,20
13933173,1484110894,048454T,NJ,PAS,2020-06-21,13,SDN,BMW,X,50750,...,-,0,NaN,NaN,NaN,NaN,NaN,2020,6,21

In [9]:
df_2020_total = pd.concat([df_2020_sp, df_2020_fa])

In [10]:
df_2020_total.to_csv('df_2020_total.csv', index = False)